// leave off @2x/@3x
// const images = {
//   logo: require('../Images/ir.png'),
//   clearLogo: require('../Images/top_logo.png'),
//   launch: require('../Images/launch-icon.png'),
//   ready: require('../Images/your-app.png'),
//   ignite: require('../Images/ignite_logo.png'),
//   igniteClear: require('../Images/ignite-logo-transparent.png'),
//   tileBg: require('../Images/tile_bg.png'),
//   background: require('../Images/BG.png'),
//   buttonBackground: require('../Images/button-bg.png'),
//   api: require('../Images/Icons/icon-api-testing.png'),
//   components: require('../Images/Icons/icon-components.png'),
//   deviceInfo: require('../Images/Icons/icon-device-information.png'),
//   faq: require('../Images/Icons/faq-icon.png'),
//   home: require('../Images/Icons/icon-home.png'),
//   theme: require('../Images/Icons/icon-theme.png'),
//   usageExamples: require('../Images/Icons/icon-usage-examples.png'),
//   chevronRight: require('../Images/Icons/chevron-right.png'),
//   hamburger: require('../Images/Icons/hamburger.png'),
//   backButton: require('../Images/Icons/back-button.png'),
//   closeButton: require('../Images/Icons/close-button.png')
// }
const images = {
  backgroundWithClouds: require('../Images/background-with-clouds.png'),
  backgroundWithPic: require('../Images/bg-with-pic.png'),
  dude1: require('../Images/dude1.png'),
  dude2: require('../Images/dude2.png'),
  dude3: require('../Images/dude3.png'),
  findDude: require('../Images/search-image-small.png'),
  postDude: require('../Images/post-image-small.png'),
  category1: require('../Images/category1.png'),
  category2: require('../Images/category2.png'),
  category3: require('../Images/category3.png'),
  category4: require('../Images/category4.png'),
  category5: require('../Images/category5.png'),
  category6: require('../Images/category6.png'),
  category7: require('../Images/category7.png'),
  category8: require('../Images/category8.png'),
  category9: require('../Images/category9.png'),
  category10: require('../Images/category10.png'),
  category11: require('../Images/category11.png'),
  category12: require('../Images/category12.png'),
  category13: require('../Images/category13.png'),
  category14: require('../Images/category14.png'),
  category15: require('../Images/category15.png'),
  buildingImg: require('../Images/building-img.png'),
  filterIcon: require('../Images/filter-icon.png'),
  dashedBorder: require('../Images/dashed-border.png'),
  jobDetailsImage: require('../Images/job-details-image.png'),
  callIcon: require('../Images/green-phone.png'),
  shareIcon: require('../Images/share-icon.png'),
  postSuccess: require('../Images/post-success-img.png'),
  pageTitleBorder: require('../Images/page-title-border.png'),
  addPhoto: require('../Images/add-photo-icon.png'),
  bellIcon: require('../Images/bell-icon.png'),
  premiumIcon: require('../Images/premium.png'),
  starIcon: require('../Images/star.png'),
  camera: require('../Images/camera.png')
}

export default images
